on: pull_request

concurrency: ci-${{ github.ref }}

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
jobs:
  validate:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.8
        terraform_wrapper: false
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format
      run: terraform fmt -check -recursive
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Setup Go Unit Test Dependencies
      working-directory: test/unit/
      run:  go get -v -t -d && go mod tidy
    
    - name: Lint Unit Tests
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: test/unit/

    - name: Terratest
      working-directory: test/unit/
      run: go test -v